// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXxwSv8IKi59ojUskno0FI0SJ4vdMvmH0',
    appId: '1:368179859084:web:405174ba02d6ef58e475a9',
    messagingSenderId: '368179859084',
    projectId: 'expense-tracker-768ba',
    authDomain: 'expense-tracker-768ba.firebaseapp.com',
    storageBucket: 'expense-tracker-768ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuWPtOA7FyrMqt24iymnsNi_3C0AlXweQ',
    appId: '1:368179859084:android:efe731a4919ad878e475a9',
    messagingSenderId: '368179859084',
    projectId: 'expense-tracker-768ba',
    storageBucket: 'expense-tracker-768ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9n6_0pxbVslO9zQDNc7ycEzHHE4bYeek',
    appId: '1:368179859084:ios:1c2987e69be44e39e475a9',
    messagingSenderId: '368179859084',
    projectId: 'expense-tracker-768ba',
    storageBucket: 'expense-tracker-768ba.firebasestorage.app',
    iosBundleId: 'com.example.tracker',
  );

}